### ISSUE TITLE
Missing wishlist icons from products

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#1]
The wishlist icon is not coming on the products.
Pls open the preview in private/ incognito tab & check for the issue.
Preview: https://wt1dadbqk2orggni-29704650796.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/175004451-9afc7dba-4550-46ca-b186-91e43f55c8ad.png)

https://wt1dadbqk2orggni-29704650796.shopifypreview.com/collections/tops
![image](https://user-images.githubusercontent.com/97726944/175004688-632e1b9e-2e4d-4006-b332-b4fa10686cc0.png)

Live: https://inamore.com/
![image](https://user-images.githubusercontent.com/97726944/175004812-77b83ead-1768-4d88-9337-4110f0c0df52.png)

https://inamore.com/collections/dresses-1
![image](https://user-images.githubusercontent.com/97726944/175004926-bea0bab6-f204-4718-91b9-cc40ea24fae7.png)

**Comment by devShivDuttChauhan** [comment]
Ready to test.
@Shoaibans sir
![image](https://user-images.githubusercontent.com/103488177/175234723-4df84a05-bd34-4aa1-abff-9301f1408b0f.png)
https://pe78hdokta8n0ec6-29704650796.shopifypreview.com/collections/dresses-1

**Comment by Shoaibans** [comment]
Fixed
![image](https://user-images.githubusercontent.com/97726944/175240372-5f61ca93-18fa-4658-b85e-6ea3e35dc73d.png)
