### ISSUE TITLE
Blurry banner in homepage

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#2]
Pls open the preview in private/ incognito tab & check for the issue.
Preview: 
![image](https://user-images.githubusercontent.com/97726944/175005665-9f8eb78f-f4f3-4a40-b6a8-174cbcbeeb0d.png)

Live: 
![image](https://user-images.githubusercontent.com/97726944/175005609-5d0ac397-85b8-4ff7-8064-ccfd75c01d8e.png)

**Comment by devShivDuttChauhan** [comment]
ready to Test

**Comment by Shoaibans** [comment]
@devShivDuttChauhan 
The banner & images in homepage are still coming blurry
![image](https://user-images.githubusercontent.com/97726944/175243541-851266be-5e6e-44e0-97b3-ff1dd7687b01.png)
![image](https://user-images.githubusercontent.com/97726944/175243590-1395073c-c9aa-4e26-8561-c9c6e06bfe52.png)
