### ISSUE TITLE
Blurry images in homepage

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#3]
Pls open the preview in private/ incognito tab & check for the issue.
Preview: 
![image](https://user-images.githubusercontent.com/97726944/175005897-66283714-88ed-4b84-83a6-152abb86bcf5.png)

Live: 
![image](https://user-images.githubusercontent.com/97726944/175006083-b6f03af4-edf6-4880-b32a-dacd85b810bf.png)

**Comment by devRitikTamrakar** [comment]
fixed
