### ISSUE TITLE
Pricing placement in preview product page

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#4]
The pricing placement is changes in preview product page.
Pls open the preview in private/ incognito tab & check for the issue.
Preview: https://wt1dadbqk2orggni-29704650796.shopifypreview.com/products/delmar-chain-white-dress?variant=39901521313946
![image](https://user-images.githubusercontent.com/97726944/175006798-73ca5411-e532-4126-9321-d416870f08e7.png)

Live: https://inamore.com/products/delmar-chain-white-dress?variant=39901521313946
![image](https://user-images.githubusercontent.com/97726944/175007219-4aa36923-33c4-4274-85fe-401f73079986.png)

**Comment by devShivDuttChauhan** [comment]
Ready to Test @Shoaibans sir
![image](https://user-images.githubusercontent.com/103488177/175234445-c45190b7-1fa2-47e9-b017-edce6245e880.png)
https://pe78hdokta8n0ec6-29704650796.shopifypreview.com/products/chloe-rope-two-piece-set?pr_prod_strat=collection_fallback&pr_rec_id=679575ba5&pr_rec_pid=7357656760474&pr_ref_pid=7307694964890&pr_seq=uniform&variant=42061546717338

**Comment by Shoaibans** [comment]
> Ready to Test @Shoaibans sir ![image](https://user-images.githubusercontent.com/103488177/175234445-c45190b7-1fa2-47e9-b017-edce6245e880.png) https://pe78hdokta8n0ec6-29704650796.shopifypreview.com/products/chloe-rope-two-piece-set?pr_prod_strat=collection_fallback&pr_rec_id=679575ba5&pr_rec_pid=7357656760474&pr_ref_pid=7307694964890&pr_seq=uniform&variant=42061546717338

Not fixed @devShivDuttChauhan 
Preview: 
![image](https://user-images.githubusercontent.com/97726944/175240915-df05fdb1-78ec-4142-ae7e-24474ca95c8a.png)

Live: 
![image](https://user-images.githubusercontent.com/97726944/175241430-92eb7696-93c4-4459-a2c5-0c8748e0c37a.png)
