### ISSUE TITLE
Broad logo in preview (Mobile)

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#5]
Pls open the preview in private/ incognito tab & check for the issue.
Preview: https://wt1dadbqk2orggni-29704650796.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/175008244-179904fd-d5c4-4701-9b82-28dce8725a8c.png)

Live: https://inamore.com/
![image](https://user-images.githubusercontent.com/97726944/175008294-9c19c631-3a68-487e-a87a-028fc601f75c.png)

**Comment by devRitikTamrakar** [comment]
it's fixed
minor difference is there bcoz of optimization
