### ISSUE TITLE
The products are not adding to the wishlist

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#6]
Pls check the video for the issue.
Pls open the preview in private/ incognito tab & check for the issue.
Video: https://www.awesomescreenshot.com/video/9585597?key=382aa3725d598c128076304fb93cfb00

**Comment by devShivDuttChauhan** [comment]
ready to Test

**Comment by Shoaibans** [comment]
Fixed
![image](https://user-images.githubusercontent.com/97726944/175241674-3b971c34-5957-41c0-95b4-d740c747163e.png)
