### ISSUE TITLE
The header is overlapping with announcement bar in Mac Device

### ISSUE THREAD

**Issue by Shoaibans** [Shoaibans/Alina-Petrone-Speed-work#7]
Pls open the preview in private/ incognito tab & check for the issue.
Preview: 
![image](https://user-images.githubusercontent.com/97726944/175012920-62f836b2-5467-4ec7-a149-ef242cc5da11.png)

Live: 
![image](https://user-images.githubusercontent.com/97726944/175012737-69067770-c8c5-48c4-be5a-e8fa9a896e30.png)

**Comment by devRitikTamrakar** [comment]
i have checked in lamda, it's working fine

**Comment by Shoaibans** [comment]
@devRitikTamrakar sir, I have got it checked in different devices and this issue is coming.
Pls check the video
Preview video: https://www.awesomescreenshot.com/video/9701335?key=9ae7755faea4c0d16ecf3507e9f73041
Live video: https://www.awesomescreenshot.com/video/9701366?key=f3dd765d0acc0c9cc3a39fbd41216391

**Comment by Shoaibans** [comment]
Fixed
![image](https://user-images.githubusercontent.com/97726944/176381470-78340977-0d37-41bb-a3c8-d05e5ac8feef.png)

**Comment by Shoaibans** [comment]
Fixed
![image](https://user-images.githubusercontent.com/97726944/176384307-a38aa4c3-fa4b-4c14-bfa2-1f7e01b3d3cb.png)
